apiVersion: v1
kind: Service
metadata:
  name: weather-service #name of the service
spec:
  selector:
    app: weather-service-pod #exact same pod name from deployment.yml
  ports:
  - port: 8080 #external port
    targetPort: 80 #internal port
  type: LoadBalancer
